COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: <your-key>

  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://<username>:<password>@<your_ip_address>:<your_port>/<your_db_name>'
  SQLALCHEMY_TRACK_MODIFICATIONS: False

  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml

  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # word报表模板文件目录
  REPORT_TEMPLATES: ./word_templates

  # 报表文件目录
  REPORT_PATH: ./report

  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  SEND_EMAIL: # Configure with your email host
    ADDRESS:
    AUTHCODE:
    PORT:
    HOST:


DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: <your-key>

PRODUCTION: &production
  <<: *common
  SECRET_KEY: <your-key>
