zh_CN: &zh
  0: "操作成功！"
  -1: 操作失败！"
  40001: "未找到对应资源！"
  40002: "请求参数不全或者无效！"
  40003: "用户名或密码错误！"
  40004: "请先登录管理系统！"
  40005: "该用户名已存在！请使用新的用户名注册！"
  40006: "邮箱地址无效！"
  40007: "邮件发送失败！"
  40008: "未找到上传文件！"
  40009: "系统不允许上传该格式的文件！"
  40010: "上传文件过大，必须小于10MB！"
  40011: "文件上传成功。已上传文件数量达到限制，移除较早上传的文件！"
  40012: "无权限访问对应资源！"
