COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: insecure
  # 页码设置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10

  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'postgresql+psycopg2://postgres:test@localhost/test'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  # 日志配置文件路径
  LOGGING_CONFIG_PATH: ./config/logging.yaml
  # 日志文件存放位置
  LOGGING_PATH: ./logs

  # word报表模板文件目录
  REPORT_TEMPLATES: ./word_templates

  # 报表文件目录
  REPORT_PATH: ./report

  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml

  # redis配置
  REDIS_EXPIRE: 60*60
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  REDIS_DB: 1
  #定时发送任务时间
  FIX_PUSH_TIME:
    - hour: 17
    - minute: 3

  # 是否开启定时任务,默认不开启
  SCHEDULER_OPEN: False

  # 定时任务配置
  SCHEDULER_API_ENABLED: False
  JOBS:
    - id: my_job
      func: app.factory:check_trade
      trigger: cron
      hour: 20
      minute: 03
    - id: my_interval_job
      func: app.factory:check_trade
      trigger: interval
      seconds: 5
  SEND_EMAIL:
    ADDRESS: # Server Email
    AUTHCODE: # Auth Code
    PORT: # Server Email Auth
    HOST: # Server Email Host



DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  REDIS_HOST: flask_redis
